server:
  port: 9090
spring:
  config:
    activate:
      on-profile: default
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:16691/STUDY?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: test
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt.secret-key: 89e94aae-c3a8-4046-a94a-aec3a8b046fb